services:
  backend-app:
    build: ./backend/
    volumes:
      - images:/app/uploads
    ports:
      - "8881:8881"
    depends_on:
      - db
  frontend-app:
    build: ./frontend/
    ports:
      - "5175:5173"
    depends_on:
      - backend-app
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1
    volumes:
      - ./base.sql:/docker-entrypoint-initdb.d/base.sql:ro
volumes:
  images:
